name: Deploy Bot to Azure

on:
  push:
    branches: [ master ]
    paths:
    - 'Bot/**'
    - '.github/workflows/**'

env:
  DOTNET_VERSION: '3.1.201'              # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies & build Using Dotnet'
      shell: pwsh
      run: |
        pushd './Bot'
        dotnet build --configuration Release
        dotnet publish -c Release -o ../output/bot
        popd

      # Deploy to Azure Web apps
    - name: 'Run Azure webapp deploy action'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: 'cora-webappbot-dev-01'
        package: './output/bot'
        publish-profile: ${{ secrets.AZURE_BOTAPP_PUBLISH_PROFILE }}
